### ISSUE TITLE
Documentation housekeeping

### ISSUE THREAD

**Issue by alexenge** [alexenge/hu-neuro-pipeline#188]
- [x] Change supported Python versions in `setup.py` (copy from https://github.com/kirstenstark/eeg-ride/blob/main/setup.py)
- [x] Update copyright year in footer
- [x] Remove my name from footer (use the lab name instead)

**Comment by SreejaMandla** [comment]
can i have this issue assigned?

**Comment by alexenge** [comment]
@SreejaMandla, sure, you're very much welcome to do this!

Please use the typical GitHub workflow where you fork the repository to your own account, make your changes on a new branch, push them to GitHub, and create a pull request from your new branch to the main repo. In case you've never done this before, there are many tutorials online, e.g., [this one](https://jarv.is/notes/how-to-pull-request-fork-github/).

Thanks in advance for your contribution and please always feel free to let me know if you need any help!

**Comment by SreejaMandla** [comment]
created the pr's, please review and let me know if you require any changes. I'd appreciate if you added the 'hacktoberfest' and 'hacktoberfest-accepted' labels to the repository/pr's.

**Comment by alexenge** [comment]
Completed via #191  and #192
